QA_Web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('website.urls', namespace='openfire-admin')),
    url(r'^chat/', include('chat_app.urls', namespace='chat-app')),
    url(r'^__debug__', include(debug_toolbar.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^staff/login/?$', views.WebSiteLoginView.as_view(), name='login'),
    url(r'^staff/logout/?$', views.WebSiteLogoutView.as_view(), name='logout'),
    url(r'^openfire/user/?$', views.OpenFireUserView.as_view(), name='openfireuser'),
    url(r'^staff/token/?$', views.UserTokenView.as_view(), name='user-token'),
]

website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.utils.translation import ugettext as _


# Create your models here.

class Action(models.Model):
    user = models.ForeignKey(User)
    action_text = models.TextField(blank=False, null=False)
    date_done = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        msg = '{} done via {}.'.format(self.action_text, self.user.username)
        return msg


class OpenFireUser(models.Model):
    # Translators: phone validation error
    phone_number_validator = RegexValidator(regex=r'^09(1|3|0)(\d){8}$',
                                            message=_('username must be a valid phone number.'))
    username = models.CharField(max_length=50, unique=True)  # , validators=[phone_number_validator])
    password = models.CharField(max_length=50)
    owner = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):

        if len(self.username) > 15:
            usn = self.username[:12] + "..."
        else:
            usn = self.username

        return "{} owned by {}".format(usn, self.owner.get_username())

website/forms.py
from django.forms import ModelForm
from .models import OpenFireUser
from chat_app.models import UserToken


class OpenFireUserForm(ModelForm):
    class Meta:
        model = OpenFireUser
        fields = ('username', 'password', 'owner',)


class UserTokenForm(ModelForm):
    class Meta:
        model = UserToken
        fields = ('bot_module_name', 'bot_class_name', 'user',)

website/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import messages
from django.shortcuts import render, Http404, redirect, get_object_or_404
from django.views import View
from .forms import OpenFireUserForm, UserTokenForm, UserToken
from .models import OpenFireUser, Action
from .openfire import rest_api
import datetime
import hashlib
from random import random


# TODO: use toastjs for error
# TODO: add option for upload custom bot class and modules
class IndexView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        users = request.user.openfireuser_set.all()
        tokens = request.user.usertoken_set.all()
        return render(request, 'website/index.html', context={'user_tokens': tokens, 'open_fire_users': users})


class WebSiteLoginView(LoginView):
    template_name = 'website/registration/login.html'
    redirect_authenticated_user = 'openfire-admin:index'


class WebSiteLogoutView(LogoutView):
    template_name = 'website/registration/logged_out.html'
    next_page = 'openfire-admin:index'


class OpenFireUserView(LoginRequiredMixin, View):
    def dispatch(self, request, *args, **kwargs):
        method = self.get_method_type(request)
        if method == "POST":
            return self.post(request, *args, **kwargs)
        elif method == "DELETE":
            return self.delete(request, *args, **kwargs)
        else:
            raise Http404

    def get_method_type(self, request):
        if request.method == "GET":
            return "GET"
        elif "_method" in request.POST:
            return request.POST["_method"].upper()
        else:
            return "POST"

    def post(self, request, *args, **kwargs):
        # create new user using form
        new_open_fire = OpenFireUserForm(request.POST)
        if new_open_fire.is_valid():
            ret = rest_api.create_new_user(request.POST["username"], request.POST["password"])
            if ret:
                new_open_fire.save()
                action = Action()
                action.user = request.user
                action.action_text = 'create openfire user: {} on {}'.format(request.POST["username"],
                                                                             datetime.datetime.now())
                action.save()
            else:
                raise Http404()
        else:
            if new_open_fire.has_error("username"):
                messages.add_message(request, messages.WARNING, new_open_fire.errors["username"][0])
            if new_open_fire.has_error("password"):
                messages.add_message(request, messages.WARNING, new_open_fire.errors["password"][0])
        return redirect('openfire-admin:index')

    def delete(self, request, *args, **kwargs):
        # delete user using request
        if "user_pk" in request.POST:
            old_open_fire = get_object_or_404(OpenFireUser, pk=request.POST["user_pk"])
            ret = rest_api.delete_user(old_open_fire.username)
            if ret:
                action = Action()
                action.user = request.user
                action.action_text = 'delete openfire user: {} on {}'.format(old_open_fire.username,
                                                                             datetime.datetime.now())
                action.save()
                old_open_fire.delete()
            else:
                raise Http404()
        return redirect('openfire-admin:index')


class UserTokenView(LoginRequiredMixin, View):
    def dispatch(self, request, *args, **kwargs):
        method = self.get_method_type(request)
        if method == "POST":
            return self.post(request, *args, **kwargs)
        elif method == "DELETE":
            return self.delete(request, *args, **kwargs)
        else:
            raise Http404

    def get_method_type(self, request):
        if request.method == "GET":
            return "GET"
        elif "_method" in request.POST:
            return request.POST["_method"].upper()
        else:
            return "POST"

    def post(self, request, *args, **kwargs):
        new_token_form = UserTokenForm(request.POST)
        print(request.POST)
        if new_token_form.is_valid():
            hsh_token_str = "hash string for:{} date:{} pk:{} rand number:{}".format(
                request.user.username, datetime.datetime.now(),
                request.user.pk, random())
            hashed = hashlib.md5(hsh_token_str.encode())
            # TODO: make use of form instead model
            # TODO: check for token existence upon generation (?)
            new_token = UserToken()
            new_token.token = hashed.hexdigest()
            new_token.bot_class_name = request.POST["bot_class_name"]
            new_token.bot_module_name = request.POST["bot_module_name"]
            new_token.user = request.user

            # TODO: check for correct class name
            from .helpers import handle_bot_file_upload as handle_upload
            handle_upload(new_token.bot_module_name, request.FILES["bot_file"])

            new_token.save()
        else:
            if new_token_form.has_error("bot_module_name"):
                messages.add_message(request, messages.ERROR, new_token_form.errors["bot_module_name"][0])
            if new_token_form.has_error("bot_class_name"):
                messages.add_message(request, messages.ERROR, new_token_form.errors["bot_class_name"][0])
        return redirect('openfire-admin:index')

    def delete(self, request, *args, **kwargs):
        if "token_pk" in request.POST:
            object_to_delete = get_object_or_404(UserToken, pk=request.POST["token_pk"])
            from .helpers import delete_local_file as delete_file
            delete_file(object_to_delete.bot_module_name)
            object_to_delete.delete()
            return redirect("openfire-admin:index")

templates/website/layouts/base_layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="OpenFire server web interface">
        <meta name="author" content="Morteza Allahpour">
        <title>WMPR Lab</title>
{#        <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">#}
        <link rel="stylesheet" href="{% static 'bs3-themes/bootstrap-Yeti-.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-rtl.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Lato:400" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <style>
            @font-face {
                font-family: 'BYekan';
                src: url('{% static 'fonts/BYekan.eot' %}') format('eot'),  /* IE6–8 */
                url('{% static 'fonts/BYekan.woff' %}') format('woff'),  /* FF3.6+, IE9, Chrome6+, Saf5.1+*/
                url('{% static 'fonts/BYekan.ttf' %}') format('truetype');  /* Saf3—5, Chrome4+, FF3.5, Opera 10+ */
            }
            body{
                font-family: 'BYekan';
            }
            {% block inline_style_sheet %}
            {% endblock %}
        </style>
    </head>
    <body>
        <nav>
        <div class="navbar navbar-inverse navbar-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'openfire-admin:index' %}">خانه</a></li>
                        {% if user.is_authenticated  %}
                        <li><a href="{% url 'openfire-admin:logout' %}">خروج</a></li>
                        {% else %}
                            <li><a href="{% url 'openfire-admin:login' %}">ورود</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        </nav>
        <main>
        <div class="container">
            {% block main_content %}

            {% endblock %}
        </div>
        </main>
        <script src="{% static 'jquery-3.1.0.min.js' %}"></script>
        <script src="{% static 'bootstrap.min.js' %}"></script>
        <script>
        $(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
            {% block inline_js %}

            {% endblock %}

        </script>
    </body>
</html>

templates/website/layouts/openfire_users.html
{% load humanize %}
{% if open_fire_users %}
        <div class="table-responsive" style="padding-top: 10px">
            <table class="table table-hover table-bordered" id="usn_table_master">
                <thead>
                <tr>
                    <th>نام کاربری</th>
                    <th>رمز عبور</th>
                    <th>تاریخ ایجاد</th>
                    <th>عملیات</th>
                </tr>
                </thead>
                <tbody id="usn_table_body">
                {% for open_fire_user in open_fire_users %}
                    <tr>
                        <td class="lato-font align-center" width="27%">{{ open_fire_user.username }}</td>
                        <td class="lato-font align-center" width="27%">{{ open_fire_user.password }}</td>
                        <td width="27%" class="align-center">{{ open_fire_user.created_on | naturaltime }}</td>
                        <td width="19%" class="align-center">
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <form action="{% url 'openfire-admin:openfireuser' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="_method" value="delete">
                                        <input type="hidden" name="user_pk" value="{{ open_fire_user.pk }}">
                                        <button type="submit" class="btn btn-danger">حذف حساب
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
    <div class="jumbotron">
        <div class="container alert alert-info">
            <p>شما کاربری ایجاد نکرده اید.</p>
        </div>
    </div>
    {% endif %}
    <form action="{% url 'openfire-admin:openfireuser' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="owner" value="{{ user.pk }}">
        <div class="form-inline">
            <div class="form-group">
                <label class="sr-only" for="usn">نام کاربری</label>
                <input type="text" class="form-control" name="username" required="true" id="usn"
                       placeholder="نام کاربری">
            </div>
            <div class="form-group">
                <label class="sr-only" for="psw">نام کاربری</label>
                <input type="text" class="form-control" name="password" required="true" id="psw"
                       placeholder="رمز عبور">
            </div>
            <button type="submit" class="btn btn-success">ساخت کاربر جدید</button>
        </div>
    </form>
    

templates/website/layouts/user_tokens.html
{% load humanize %}
{% if user_tokens %}
    <div class="table-responsive" style="padding-top: 10px">
        <table class="table table-hover table-bordered" id="usn_table_master">
            <thead>
            <tr>
                <th>نام ماژول</th>
                <th>نام کلاس</th>
                <th>نشانه</th>
                <th>حداکثر کوئری</th>
                <th>تاریخ ایجاد</th>
                <th>عملیات</th>
            </tr>
            </thead>
            <tbody id="token_table_body">
            {% for token in user_tokens %}
                <tr>
                    <td class="lato-font align-center" width="10%">{{ token.bot_module_name }}</td>
                    <td class="lato-font align-center" width="10%">{{ token.bot_class_name }}</td>
                    <td class="lato-font align-center">
                        <pre><code>{{ token.token }}</code></pre>
                    </td>
                    <td class="lato-font align-center" width="5%" style="direction:ltr;">{{ token.max_queries }}</td>
                    <td class="align-center" width="15%">{{ token.created_on | naturaltime }}</td>
                    <td class="align-center" width="25%">
                        <div class="form-group col-md-5">
                            <div class="">
                                <form action="{% url 'openfire-admin:user-token' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="_method" value="delete">
                                    <input type="hidden" name="token_pk" value="{{ token.pk }}">
                                    <button type="submit" class="btn btn-danger">حذف توکن
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </div>
                        </div>

                        <div class="col-md-5">
                            <input type="hidden" name="_method" value="delete">
                            <input type="hidden" name="token_pk" value="{{ token.pk }}">
                            <a data-toggle="modal" href="#modal-{{ forloop.counter }}-{{ token.token }}" class="btn btn-info">مشاهده راهنما
                                <i class="fa fa-info-circle"></i>
                            </a>
                        </div>

                        <div class="modal fade" id="modal-{{ forloop.counter }}-{{ token.token }}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                            &times;
                                        </button>
                                        <h4 class="modal-title">نحوه استفاده</h4>
                                    </div>
                                    <div class="modal-body">
                                        Your unique api token help
                                        <pre><code>{{ token.token }}</code></pre>

                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">بستن
                                        </button>
                                    </div>
                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div><!-- /.modal -->


                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <div class="jumbotron">
        <div class="container alert alert-info">
            <p> شما هنوز هیچ رباتی ایجاد نکرده اید.</p>
        </div>
    </div>
{% endif %}
<form enctype="multipart/form-data" action="{% url 'openfire-admin:user-token' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="user" value="{{ user.pk }}">
    <div class="form-inline">
        <div class="form-group">
            <label class="sr-only" for="bot_module_name">نام ماژول روبات</label>
            <input type="text" style="direction: ltr;" data-toggle="tooltip" data-title="نام ماژول روبات"
                   class="form-control lato-font" name="bot_module_name" id="bot_module_name" value="base_bot"
                   placeholder="نام ماژول روبات">
        </div>
        <div class="form-group">
            <label class="sr-only" for="bot_class_name">نام کلاس روبات</label>
            <input type="text" style="direction: ltr;" data-toggle="tooltip" data-title="نام کلاس روبات"
                   class="form-control lato-font" name="bot_class_name" id="bot_class_name" value="SampleBot"
                   placeholder="نام کلاس روبات">
        </div>
        <div class="form-group">
            <label class="sr-only" for="bot_file">فایل روبات</label>
            <input type="file" class="form-control" name="bot_file" id="bot_file"
                   placeholder="فایل روبات">
        </div>
        <button type="submit" class="btn btn-success">ایجاد روبات جدید</button>
    </div>
</form>